export const EVENT_OPTIONS: String[] = [
  'field goal missed',
  'field goal made',
  '3pt field goal missed',
  '3pt field goal made',
  'putback missed',
  'putback made',
  'assist',
  'assist attempt',
  'block',
  'offensive rebound',
  'defensive rebound',
  'deadball rebound',
  'goal tending',
  'freethrow made',
  'freethrow missed',
  'freethrow violation',
  'turnover',
  'steal',
  'defensive assist',
  'jumpball',
  'jumpball win',
  'jumpball loss',
  'foul',
  'foul drawn',
  'offensive foul',
  'charge',
  'charge taken',
  'intentional foul',
  'technical foul',
  'coach technical foul',
  'ddministrative technical foul',
  'full timeout',
  'half timeout',
  'official timeout',
  'media timeout',
  'injury timeout'
];