export const EVENT_OPTIONS: {} = {
  'fieldgoalMissed': 0,
  'fieldgoalMade': 1,
  'putbackMissed': 2,
  'putbackMade': 3,
  'assist': 4,
  'assistAttempt': 5,
  'offensiveRebound': 6,
  'defensiveRebound': 7,
  'deadballRebound': 8,
  'goalTending': 9,
  'freethrowMade': 10,
  'freethrowMissed': 11,
  'violation': 12,
  'turnover': 13,
  'steal': 14,
  'jumpball': 15,
  'jumpballWin': 16,
  'jumpballLoss': 17,
  'foul': 18,
  'foulDrawn': 19,
  'offensiveFoul': 20,
  'chargeTaken': 21,
  'technicalFoul': 22,
  'fullTimeout': 23,
  'halfTimeout': 24,

};